CREATE OR REPLACE DATABASE WAREHOUSE_DB;

CREATE OR REPLACE SCHEMA WAREHOUSE_DB.BRONZE;
CREATE OR REPLACE SCHEMA WAREHOUSE_DB.SILVER;
CREATE OR REPLACE SCHEMA WAREHOUSE_DB.GOLD;

CREATE TABLE bronze.crm_cust_info (
    cst_id INT,
    cst_key NVARCHAR(50),
    cst_firstname NVARCHAR(50),
    cst_lastname NVARCHAR(50),
    cst_material_status NVARCHAR(50),
    cst_gndr NVARCHAR(50),
    cst_create_date DATE
);
